server:
  applicationConnectors:
  - type: http
    port: 8081
  adminConnectors:
  - type: http
    port: 9081

wavefrontReporterMechanism: direct-ingestion

# Report via Direct Ingestion
wavefrontServer: http://localhost:8080
token: 83b67360-b57f-4422-b592-17f9691fd28b

# Report via Proxy
host: localhost
port: 2878

application: wavefront
cluster: doordash-cluster
service: doordash
shard: primary

tags:
  location: SF
  env: Staging