server:
  applicationConnectors:
  - type: http
    port: 8085
  adminConnectors:
  - type: http
    port: 9085

wavefrontReporterMechanism: direct-ingestion

# Report via Direct Ingestion
wavefrontServer: http://localhost:8080
token: 33a4bbaa-db07-4de9-a2b6-5e4fb4ede5d0

# Report via Proxy
host: localhost
port: 2878

application: wavefront
cluster: doordash-cluster
service: doordash
shard: primary

tags:
  location: SF
  env: Staging