server:
  applicationConnectors:
  - type: http
    port: 8083
  adminConnectors:
  - type: http
    port: 9083

wavefrontReporterMechanism: proxy

# Report via Direct Ingestion
wavefrontServer: localhost
token: <TOKEN>

# Report via Proxy
host: localhost
port: 2878